[package]
name = "mgi_read_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
fastq = "0.6.0"
rust-htslib = "0.39.5"
clap = "3.2.20"
